# Array Mathematics
Basic mathematical functions operate element-wise on arrays. They are available both as operator overloads and as functions in the NumPy module.<br>
> `import numpy`<br><br>
`a = numpy.array([1,2,3,4], float)`<br>
`b = numpy.array([5,6,7,8], float)`<br><br>
`print a + b                     #[  6.   8.  10.  12.]`<br>
`print numpy.add(a, b)           #[  6.   8.  10.  12.]`<br><br>
`print a - b                     #[-4. -4. -4. -4.]`<br>
`print numpy.subtract(a, b)      #[-4. -4. -4. -4.]`<br><br>
`print a * b                     #[  5.  12.  21.  32.]`<br>
`print numpy.multiply(a, b)      #[  5.  12.  21.  32.]`<br><br>
`print a / b                     #[ 0.2         0.33333333  0.42857143  0.5       ]`<br>
`print numpy.divide(a, b)        #[ 0.2         0.33333333  0.42857143  0.5       ]`<br><br>
`print a % b                     #[ 1.  2.  3.  4.]`<br>
`print numpy.mod(a, b)           #[ 1.  2.  3.  4.]`<br><br>
`print a**b                      #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]`<br>
`print numpy.power(a, b)         #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]`<br>
***

### Task

You are given two integer arrays, $A$ and $B$ of dimensions $N$X$M$.<br>
Your task is to perform the following operations:<br>

1. Add ($A$ + $B$)
2. Subtract ($A$ - $B$)
3. Multiply ($A$ * $B$)
4. Integer Division ($A$ / $B$)
5. Mod ($A$ % $B$)
6. Power ($A$ ** $B$)

### Note
There is a method numpy.floor_divide() that works like numpy.divide() except it performs a floor division.

#### Input Format

The first line contains two space separated integers, $N$ and $M$.<br>
The next $N$ lines contains $M$ space separated integers of array $A$.<br>
The following $N$ lines contains $M$ space separated integers of array $B$.

#### Output Format

Print the result of each operation in the given order under Task.

### Sample Input

> `1 4`<br>
`1 2 3 4`<br>
`5 6 7 8`

### Sample Output

> `[[ 6  8 10 12]]`<br>
`[[-4 -4 -4 -4]]`<br>
`[[ 5 12 21 32]]`<br>
`[[0 0 0 0]]`<br>
`[[1 2 3 4]]`<br>
`[[    1    64  2187 65536]]`<br>

Use // for division in Python 3.

In [1]:
import numpy as np

n, m = map(int, input().split())
a = np.array([input().split() for _ in range(n)], int)
b = np.array([input().split() for _ in range(n)], int)

print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(a**b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
