# Floor, Ceil and Rint
### [floor](https://numpy.org/doc/stable/reference/generated/numpy.floor.html#numpy-floor)
The tool floor returns the floor of the input element-wise.<br>
The floor of $x$ is the largest integer $i$ where $i≤x$.<br>

> `import numpy`<br><br>
`my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])`<br>
`print numpy.floor(my_array)         #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]`<br>

### [ceil](https://numpy.org/doc/stable/reference/generated/numpy.ceil.html#numpy-ceil)
The tool ceil returns the ceiling of the input element-wise.<br>
The ceiling of $x$ is the smallest integer $i$ where $i≤x$.<br>

> `import numpy`<br><br>
`my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])`<br>
`print numpy.ceil(my_array)          #[  2.   3.   4.   5.   6.   7.   8.   9.  10.]`<br>

### [rint](https://numpy.org/doc/stable/reference/generated/numpy.rint.html)
The rint tool rounds to the nearest integer of input element-wise.<br>

> `import numpy`<br><br>
`my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])`<br>
`print numpy.rint(my_array)          #[  1.   2.   3.   4.   6.   7.   8.   9.  10.]`<br>
****

### Task
You are given a 1-D array, $A$. Your task is to print the $floor$, $ceil$ and $rint$ of all the elements of $A$.

### Note
In order to get the correct output format, add the line **numpy.set_printoptions(legacy='1.13')** below the numpy import.

### Input Format

A single line of input containing the space separated elements of array $A$.

### Output Format

On the first line, print the $floor$ of A.<br>
On the second line, print the $ceil$ of A.<br>
On the third line, print the $rint$ of A.

### Sample Input

> `1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9`

### Sample Output

> `[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]`<br>
`[  2.   3.   4.   5.   6.   7.   8.   9.  10.]`<br>
`[  1.   2.   3.   4.   6.   7.   8.   9.  10.]`<br>

In [1]:
import numpy as np
np.set_printoptions(sign=' ')

arr = np.array(input().split(), float)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
