# Zeros and Ones
### [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy-zeros)

The zeros tool returns a new array with a given shape and type filled with $0$'s.<br>

> `import numpy`<br><br>
`print numpy.zeros((1,2))                    #Default type is float`<br>
`#Output : [[ 0.  0.]] `<br><br>
`print numpy.zeros((1,2), dtype = numpy.int) #Type changes to int`<br>
`#Output : [[0 0]]`<br>

### [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy-ones)

The ones tool returns a new array with a given shape and type filled with $1$'s.<br>

> `import numpy`<br><br>
`print numpy.ones((1,2))                    #Default type is float`<br>
`#Output : [[ 1.  1.]]`<br><br> 
`print numpy.ones((1,2), dtype = numpy.int) #Type changes to int`<br>
`#Output : [[1 1]]`<br>   
***

### Task

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

### Input Format

A single line containing the space-separated integers.

### Constraints

$ 1 ≤ each integer ≤ 3 $

### Output Format

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

### Sample Input 0

> `3 3 3`

### Sample Output 0

`[[[0 0 0]`<br>
`  [0 0 0]`<br>
`  [0 0 0]]`<br><br>

` [[0 0 0]`<br>
`  [0 0 0]`<br>
`  [0 0 0]]`<br><br>

` [[0 0 0]`<br>
`  [0 0 0]`<br>
`  [0 0 0]]]`<br>
`[[[1 1 1]`<br>
`  [1 1 1]`<br>
`  [1 1 1]]`<br><br>

` [[1 1 1]`<br>
`  [1 1 1]`<br>
`  [1 1 1]]`<br><br>

` [[1 1 1]`<br>
`  [1 1 1]`<br>
`  [1 1 1]]]`<br><br>
  
### Explanation 0

Print the array built using numpy.zeros and numpy.ones tools and you get the result as shown.

In [1]:
import numpy as np

arr_shape = tuple(map(int, input().split()))
print(np.zeros(arr_shape, dtype=np.int))
print(np.ones(arr_shape, dtype=np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
